source "https://rubygems.org"

# Web framework
gem "puma"
gem "roda", "~> 3.9"

# Structure
gem "dry-configurable"
gem "dry-inflector"
gem "dry-initializer"
gem "dry-matcher"
gem "dry-monads"
gem "dry-system"
gem "dry-validation"
gem "dry-view"

# Rendering
gem "tilt", "~> 2.0"
gem "erubi"
gem "forme", "~> 1.8"

# Database
gem "rom", "~> 5.0"
gem "rom-sql"
gem "sqlite3"

# Attachments
gem "shrine", github: "shrinerb/shrine"
gem "shrine-rom", path: ".."
gem "image_processing", "~> 1.8"
gem "marcel"
gem "fastimage"
gem "dry-monitor"

# Background jobs
gem "sucker_punch", "~> 2.0"

# Development
gem "rake"
gem "pry"
